seed: 42

train:
  timesteps: 36000
  optimize_freq: 1
  update_per_opt: 8

buffer:
  buffer_size: 1024

agent:
  class: SafetyQ
  batch_size: 16384
  learning_starts: 64
  grad_norm_clip: 0.0

  discount_factor: 0.9
  gamma_schedule:
    enabled: true
    period: 10000
    decay: 0.5
    end_value: 0.99
    goal_value: 0.99

  alpha: 0.05
  learn_alpha: true

  critic_learning_rate: 3.0e-04
  actor_learning_rate: 1.0e-04
  alpha_learning_rate: 2.0e-05
  tau: 0.01
  update_period: 2

  threshold: 0.0

  model:
    min_log_std: -10.0
    max_log_std: 1.0

  experiment:
    directory: "r1_intervention"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto
